### ISSUE TITLE
fail to open file TmpGifs/312733417272.gif

### ISSUE THREAD

**Issue by mictadlo** [fikipollo/blast-docker#1]
Hi,
The standard blastn result page output `fail to open file TmpGifs/312733417272.gif` rather showing the alignment graphic.

What did I miss?

Thank you in advance,

Michal

**Comment by mictadlo** [comment]
Solution is  `chmod o+w  /var/www/html/blast/TmpGifs/`

**Comment by fikipollo** [comment]
Fixed in commit 0ef4462

thanks for the solution!
